import createClient, { type Middleware } from "openapi-fetch";
import type { AsyncMessagePublisherI } from "../async-messages/async-message-publisher";
import type { paths } from "./girobet-backend-generated-http-client/openapi-typescript"; // generated by openapi-typescript
import { ErrorJurisdictionIsNotSupported } from "~/modules/jurisdictions/domain/ErrorJurisdictionIsNotSupported";
import { EmitOpenJurisdictionModalOnJurisdictionNotSupported } from "~/modules/jurisdictions/infra/ui/EmitOpenJurisdictionModalOnJurisdictionNotSupported";

const createMiddlewareJurisdictionErrorHandler: (asyncMessagePublisher: AsyncMessagePublisherI) => Middleware = (asyncMessagePublisher: AsyncMessagePublisherI) => {
  const emitOpenJurisdictionModalOnJurisdictionNotSupported = new EmitOpenJurisdictionModalOnJurisdictionNotSupported(asyncMessagePublisher);
  return {
    async onResponse({ response }) {
      if (response.ok || !response.headers.get("content-type")?.includes("application/json")) {
        return;
      }

      const jsonResponse = await response.clone().json();
      if (jsonResponse.code) {
        let error: ErrorJurisdictionIsNotSupported;
        switch (jsonResponse.code) {
          case "JURISDICTION_NOT_SUPPORTED":
            error = ErrorJurisdictionIsNotSupported.newNotSupported(jsonResponse.metadata.jurisdiction);
            await emitOpenJurisdictionModalOnJurisdictionNotSupported.handle(error);
            return;

          case "JURISDICTION_NOT_SUPPORTED_ALTERNATIVE_SITE":
            error = ErrorJurisdictionIsNotSupported.newWithAlternatives(
              jsonResponse.metadata.jurisdiction,
              [jsonResponse.metadata.alternative_site.redirect_url],
            );
            await emitOpenJurisdictionModalOnJurisdictionNotSupported.handle(error);
            return;

          case "JURISDICTION_NOT_SUPPORTED_NETWORK_CONFIGURATION":
            error = ErrorJurisdictionIsNotSupported.newNotSupportedForUser(jsonResponse.metadata.jurisdiction);
            await emitOpenJurisdictionModalOnJurisdictionNotSupported.handle(error);
            return;

          default:
            return;
        }
      }
    },
  };
};

export const createBackendOpenApiClient = (clientOptions: { baseUrl: string; userJurisdiction?: string; headers?: Record<string, string> }, asyncMessagePublisher: AsyncMessagePublisherI) => {
  const client = createClient<paths>({ baseUrl: clientOptions.baseUrl, credentials: "include", headers: {
    ...(clientOptions.userJurisdiction ? { "CF-IPCountry": clientOptions.userJurisdiction } : {}),
    "Content-Type": "application/json",
    "User-Agent": "girobet-frontend",
    ...clientOptions.headers,
  } });
  client.use(createMiddlewareJurisdictionErrorHandler(asyncMessagePublisher));
  return client;
};
