import type { Config } from "tailwindcss";

export default <Partial<Config>>{
  content: ["./pages/**/*.vue", "./components/**/*.vue", "./constants/**/*.ts"],
  theme: {
    fontSize: {
      base: "0.875rem",
      xs: "0.656rem",
      sm: "0.765rem",
      lg: "0.984rem",
      xl: "1.093rem",
      "2xl": "1.312rem",
      "3xl": "1.64rem",
      "4xl": "1.968rem",
      "5xl": "2.625rem",
      "6xl": "3.28rem",
      "7xl": "3.937rem",
      "8xl": "5.25rem",
      "9xl": "7rem",
    },
    colors: ({ colors }) => ({
      inherit: colors.inherit,
      current: colors.current,
      transparent: colors.transparent,
      black: colors.black,
      white: colors.white,
      default: "rgba(var(--giro-bg), <alpha-value>)",
      emphasis: "rgba(var(--giro-bg-emphasis), <alpha-value>)",
      subtle: "rgba(var(--giro-bg-subtle), <alpha-value>)",
      muted: "rgba(var(--giro-bg-muted), <alpha-value>)",
      warning: "rgba(var(--giro-bg-warning), <alpha-value>)",
      success: "rgba(var(--giro-bg-success), <alpha-value>)",
      text: {
        emphasis: "rgba(var(--giro-bg-text-emphasis), <alpha-value>)",
        subtle: "rgba(var(--giro-bg-text-subtle), <alpha-value>)",
      },
      active: "rgba(var(--giro-bg-active), <alpha-value>)",
      alert: {
        success: "var(--giro-alert-success)",
        warning: "var(--giro-alert-warning)",
        error: "var(--giro-alert-error)",
        info: "var(--giro-alert-info)",
      },
      button: {
        primary: "var(--giro-button-primary)",
        "primary-hover": "var(--giro-button-primary-hover)",
        secondary: "var(--giro-button-secondary)",
        "secondary-hover": "var(--giro-button-secondary-hover)",
        emphasis: "var(--giro-button-emphasis)",
        "emphasis-hover": "var(--giro-button-emphasis-hover)",
        subtle: "var(--giro-button-subtle)",
        "subtle-hover": "var(--giro-button-subtle-hover)",
        danger: "var(--giro-button-danger)",
        "danger-hover": "var(--giro-button-danger-hover)",
      },
      promo: {
        primary: "var(--color-promo-primary)",
      },
    }),
    textColor: ({ colors }) => ({
      inherit: colors.inherit,
      current: colors.current,
      transparent: colors.transparent,
      black: colors.black,
      white: colors.white,
      primary: "var(--giro-text-primary)",
      "primary-hover": "var(--giro-text-primary-hover)",
      default: "var(--giro-text)",
      subtle: "var(--giro-text-subtle)",
      "subtle-light": "var(--giro-text-subtle-light)",
      emphasis: "var(--giro-text-emphasis)",
      alert: {
        success: "var(--giro-alert-text-success)",
        warning: "var(--giro-alert-text-warning)",
        error: "var(--giro-alert-text-error)",
        info: "var(--giro-alert-text-info)",
      },
      button: {
        primary: "var(--giro-button-text-primary)",
        secondary: "var(--giro-button-text-secondary)",
        emphasis: "var(--giro-button-text-emphasis)",
        subtle: "var(--giro-button-text-subtle)",
        danger: "var(--giro-button-text-danger)",
      },
      promo: {
        primary: "var(--color-promo-text-primary)",
      },
    }),
    borderRadius: {
      none: "0px",
      sm: "0.2rem",
      DEFAULT: "0.4rem",
      lg: "0.8rem",
      full: "9999px",
    },
    extend: {
      backgroundImage: {
        "button-primary": "var(--giro-button-primary)",
        "button-primary-hover": "var(--giro-button-primary-hover)",
        "button-secondary": "var(--giro-button-secondary)",
        "button-secondary-hover": "var(--giro-button-secondary-hover)",
        "button-emphasis": "var(--giro-button-emphasis)",
        "button-emphasis-hover": "var(--giro-button-emphasis-hover)",
      },
      screens: {
        xs: "400px",
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
