import type { Config } from "tailwindcss";

export default <Partial<Config>>{
  content: ["./pages/**/*.vue", "./components/**/*.vue", "./constants/**/*.ts"],
  theme: {
    fontSize: {
      base: "0.875rem",
      xs: "0.656rem",
      sm: "0.765rem",
      lg: "0.984rem",
      xl: "1.093rem",
      "2xl": "1.312rem",
      "3xl": "1.64rem",
      "4xl": "1.968rem",
      "5xl": "2.625rem",
      "6xl": "3.28rem",
      "7xl": "3.937rem",
      "8xl": "5.25rem",
      "9xl": "7rem",
    },
    extend: {
      colors: {
        default: "rgba(var(--giro-bg), <alpha-value>)",
        emphasis: "rgba(var(--giro-bg-emphasis), <alpha-value>)",
        subtle: "rgba(var(--giro-bg-subtle), <alpha-value>)",
        muted: "rgba(var(--giro-bg-muted), <alpha-value>)",
        info: "rgba(var(--giro-bg-info), <alpha-value>)",
        warning: "rgba(var(--giro-bg-warning), <alpha-value>)",
        success: "rgba(var(--giro-bg-success), <alpha-value>)",
        text: {
          emphasis: "rgba(var(--giro-bg-text-emphasis), <alpha-value>)",
          subtle: "rgba(var(--giro-bg-text-subtle), <alpha-value>)",
        },
        active: "rgba(var(--giro-bg-active), <alpha-value>)",
        button: {
          primary: "var(--giro-button-primary)",
          "primary-hover": "var(--giro-button-primary-hover)",
          secondary: "var(--giro-button-secondary)",
          "secondary-hover": "var(--giro-button-secondary-hover)",
          emphasis: "var(--giro-button-emphasis)",
          "emphasis-hover": "var(--giro-button-emphasis-hover)",
          subtle: "var(--giro-button-subtle)",
          "subtle-hover": "var(--giro-button-subtle-hover)",
          danger: "var(--giro-button-danger)",
        },
        "alert-success": "var(--giro-alert-success)",
        "alert-warning": "var(--giro-alert-warning)",
        "alert-error": "var(--giro-alert-error)",
        "alert-info": "var(--giro-alert-info)",
      },
      backgroundImage: {
        "button-primary": "var(--giro-button-primary)",
        "button-primary-hover": "var(--giro-button-primary-hover)",
        "button-secondary": "var(--giro-button-secondary)",
        "button-secondary-hover": "var(--giro-button-secondary-hover)",
        "button-emphasis": "var(--giro-button-emphasis)",
        "button-emphasis-hover": "var(--giro-button-emphasis-hover)",
      },
      textColor: {
        default: "var(--giro-text)",
        subtle: "var(--giro-text-subtle)",
        "subtle-light": "var(--giro-text-subtle-light)",
        emphasis: "var(--giro-text-emphasis)",
        info: "var(--giro-text-info)",
        warning: "var(--giro-text-warning)",
        success: "var(--giro-text-success)",
        alert: {
          success: "var(--giro-text-alert-success)",
          warning: "var(--giro-text-alert-warning)",
          error: "var(--giro-text-alert-error)",
          info: "var(--giro-text-alert-info)",
        },
        button: {
          primary: "var(--giro-button-text-primary)",
          secondary: "var(--giro-button-text-secondary)",
          emphasis: "var(--giro-button-text-emphasis)",
          subtle: "var(--giro-button-text-subtle)",
        },
      },
      fill: {
        default: "var(--giro-text)",
        subtle: "var(--giro-text-subtle)",
        emphasis: "var(--giro-text-emphasis)",
        button: {
          primary: "var(--giro-button-text-primary)",
          secondary: "var(--giro-button-text-secondary)",
          emphasis: "var(--giro-button-text-emphasis)",
        },
      },
      borderRadius: {
        default: "var(--giro-border-radius)",
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
