<!--

 This component is should follow the instructions given by Chad on WhatsApp on 2025-05-26:

    Dear Client,

    Please find below the newly issued validation code snippet for ["zamba.bet"]. The snippet will visualize the Anjouan Licensing Services Inc. logo. This is a mandatory requirement and the snippet should be presented all times in the website footer. You can easily position or resize it by styling an outside container element around it. It’s important to add it the same order that is provided below. The div tag should be added first and right after it the script tag.

    <div id="anj-baee18f7-63ae-4aa0-b5d7-8160149e921b" data-anj-seal-id="baee18f7-63ae-4aa0-b5d7-8160149e921b" data-anj-image-size="128" data-anj-image-type="basic-small"></div>
    <script type="text/javascript" src="https://baee18f7-63ae-4aa0-b5d7-8160149e921b.snippet.anjouangaming.org/anj-seal.js"></script>

    In case the website footer is generated by a client-side framework (e.g. AngularJS, ReactJS, etc), please ignore the above guide and follow these simple instructions below.

    1) Add the script to the <head> of the html
    <script type="text/javascript" src="https://baee18f7-63ae-4aa0-b5d7-8160149e921b.snippet.anjouangaming.org/anj-seal.js"></script>

    2) Add the logo container to your client side template:
    <div id="anj-baee18f7-63ae-4aa0-b5d7-8160149e921b" data-anj-seal-id="baee18f7-63ae-4aa0-b5d7-8160149e921b" data-anj-image-size="128" data-anj-image-type="basic-small"></div>

    3) Execute anj_baee18f7_63ae_4aa0_b5d7_8160149e921b.init() inside the relevant hook of your client side framework for the component loading the template - e.g. for AngularJS 1 and 2 that would be onInit()

    NOTE: If the licensed website requires login credentials for accessing it and it is in production state you are required to add the snippet on the login page and in the footer of the site as well.

    Commonly seen issues with the integration:

    In case the website footer is generated by a client-side framework (e.g. AngularJS, ReactJS, etc), the div tag is added, script tag, and the init hook is executed but still the logo is not visible, please make sure that all elements are added according to the instructions above and the init hook is executed.  You can easily validate that the hook is not executed properly by clicking the right mouse/trackpad button and hit “Inspect” menu of the browser. Then in the “Console” tab of the inspect window execute anj_baee18f7_63ae_4aa0_b5d7_8160149e921b.init() manually. If the logo visualizes after this action then this element is missing in your code, maybe you need to review it and add it in the correct hook.

    Best Regards,
    Anjouan Licensing Services Inc. Compliance Team

 -->
<script setup lang="ts">
const store = useSiteStore();

const licenseStatus = ref<"active" | "inactive">("inactive");

onMounted(() =>
  licenseStatus.value = store.activateAnjouanLicenseIfAvailable(),
);
</script>

<template>
  <div
    v-show="licenseStatus !== 'inactive'"
    id="anj-baee18f7-63ae-4aa0-b5d7-8160149e921b"
    data-anj-seal-id="baee18f7-63ae-4aa0-b5d7-8160149e921b"
    data-anj-image-size="128"
    data-anj-image-type="basic-small"
    class="flex items-center justify-center"
  />
</template>
