apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ .Release.Name }}"
spec:
  commonName: "{{ .Values.config.public_domain }}"
  dnsNames:
    - "{{ .Values.config.public_domain }}"
  duration: 2160h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: girobet
  renewBefore: 360h0m0s
  secretName: "{{ .Release.Name }}-certificate"
