apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  NUXT_API_BASE_URL: "http://{{ .Values.config.internal_api_domain }}"
  NUXT_PUBLIC_API_CLIENT_PROTOCOL: "https://"
  NUXT_PUBLIC_ENV: "production"