apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}"
data:
  NUXT_PUBLIC_API_BASE_URL: https://api.girobet.vip

  # Games module
  NUXT_PUBLIC_GAMES_API_BASE_URL_CLIENT: "https://api.girobet.vip"
  NUXT_PUBLIC_GAMES_API_BASE_URL_SERVER: "http://girobet-api.default.svc.cluster.local"

  # Signup flow module
  NUXT_PUBLIC_SIGNUP_FLOWS_IDS_CLIENT_REPO: "local_storage"
  NUXT_PUBLIC_SIGNUP_FLOWS_API_BASE_URL_CLIENT: "https://api.girobet.vip"
  NUXT_PUBLIC_SIGNUP_FLOWS_API_BASE_URL_SERVER: "http://girobet-api.default.svc.cluster.local"

  # Users module
  NUXT_PUBLIC_USERS_AUTHENTICATED_REPO_BASE_URL_CLIENT: "https://api.girobet.vip"
  NUXT_PUBLIC_USERS_AUTHENTICATED_REPO_BASE_URL_SERVER: "http://girobet-api.default.svc.cluster.local"

  # Wallet module
  NUXT_PUBLIC_WALLETS_API_BASE_URL_CLIENT: "https://api.girobet.vip"
  NUXT_PUBLIC_WALLETS_API_BASE_URL_SERVER: "http://girobet-api.default.svc.cluster.local"
