apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}"
data:
  NUXT_PUBLIC_BASE_URL: "https://{{ .Values.config.public_domain }}"
  NUXT_PUBLIC_API_BASE_URL_CLIENT: "https://{{ .Values.config.public_api_domain }}"
  NUXT_PUBLIC_API_BASE_URL_SERVER: "http://{{ .Values.config.internal_api_domain }}"

  NUXT_PUBLIC_ERROR_CAPTURING_ENABLED: "true"
  LOG_LEVEL: "info" # Some libraries use it to set their log level. Should match the below "NUXT_PUBLIC_LOG_LEVEL"
  NUXT_PUBLIC_LOG_LEVEL: "info"
  NUXT_PUBLIC_SERVICE_NAME: "frontend"

  NUXT_PUBLIC_SIGNUP_FLOWS_IDS_CLIENT_REPO: "local_storage"

  NUXT_SITE_NAME: "{{ .Values.config.site_name }}"

  NUXT_PUBLIC_API_MODE: "api"
  NUXT_PUBLIC_GAMES_API_MODE: "api"
  NUXT_PUBLIC_SIGNUP_FLOWS_API_MODE: "api"
  NUXT_PUBLIC_USERS_API_MODE: "api"
  NUXT_PUBLIC_SITES_API_MODE: "api"
  NUXT_PUBLIC_WALLETS_API_MODE: "api"
  NUXT_PUBLIC_PROVIDERS_API_MODE: "api"
  NUXT_PUBLIC_KYC_API_MODE: "api"
  NUXT_PUBLIC_TRACKING_API_MODE: "api"

  NUXT_PUBLIC_TRACKING_FINGERPRINT_JS_PUBLIC_API_KEY: "ovcHpM99bHR6cWYgKHlA" # From the FingerprintJS "production" environment
  NUXT_PUBLIC_TRACKING_FINGERPRINT_JS_SCRIPT_URL: "https://{{ .Values.config.public_fingerprint_js_script_domain }}/EkkWvBzKSGMIQZw4/1qDponqL8OE8LDgt" # Goten from the FingerprintJS "Get Started" page

  # OTEL configuration
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://k8s-monitoring-alloy.monitoring.svc.cluster.local:4317"
  OTEL_BSP_SCHEDULE_DELAY: "2000"
  OTEL_BSP_MAX_EXPORT_BATCH_SIZE: "1024"
  OTEL_BSP_MAX_QUEUE_SIZE: "4096"
  OTEL_BSP_EXPORT_TIMEOUT: "15000"
  OTEL_BSP_MAX_CONCURRENT_EXPORTS: "2"
