apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}"
data:
  NUXT_PUBLIC_BASE_URL: "https://{{ .Values.config.public_domain }}"
  NUXT_PUBLIC_API_BASE_URL_CLIENT: "https://{{ .Values.config.public_api_domain }}"
  NUXT_PUBLIC_API_BASE_URL_SERVER: "https://{{ .Values.config.internal_api_domain }}"
  NUXT_PUBLIC_WEBSOCKET_API_BASE_URL: "https://{{ .Values.config.public_api_domain }}/ws/connect"

  NUXT_PUBLIC_ERROR_CAPTURING_ENABLED: "true"
  LOG_LEVEL: "debug" # Some libraries use it to set their log level. Should match the below "NUXT_PUBLIC_LOG_LEVEL"
  NUXT_PUBLIC_LOG_LEVEL: "debug"
  NUXT_PUBLIC_SERVICE_NAME: "frontend"

  # Games module
  NUXT_PUBLIC_GAMES_API_BASE_URL_CLIENT: "https://{{ .Values.config.public_api_domain }}"
  NUXT_PUBLIC_GAMES_API_BASE_URL_SERVER: "http://{{ .Values.config.internal_api_domain }}"

  # Signup flow module
  NUXT_PUBLIC_SIGNUP_FLOWS_IDS_CLIENT_REPO: "local_storage"
  NUXT_PUBLIC_SIGNUP_FLOWS_API_BASE_URL_CLIENT: "https://{{ .Values.config.public_api_domain }}"
  NUXT_PUBLIC_SIGNUP_FLOWS_API_BASE_URL_SERVER: "http://{{ .Values.config.internal_api_domain }}"

  # Users module
  NUXT_PUBLIC_USERS_AUTHENTICATED_REPOSITORY_BASE_URL_CLIENT: "https://{{ .Values.config.public_api_domain }}"
  NUXT_PUBLIC_USERS_AUTHENTICATED_REPOSITORY_BASE_URL_SERVER: "http://{{ .Values.config.internal_api_domain }}"

  # Wallet module
  NUXT_PUBLIC_WALLETS_API_BASE_URL_CLIENT: "https://{{ .Values.config.public_api_domain }}"
  NUXT_PUBLIC_WALLETS_API_BASE_URL_SERVER: "http://{{ .Values.config.internal_api_domain }}"

  # Providers domain
  NUXT_PUBLIC_PROVIDERS_API_BASE_URL_CLIENT: "https://{{ .Values.config.public_api_domain }}"
  NUXT_PUBLIC_PROVIDERS_API_BASE_URL_SERVER: "http://{{ .Values.config.internal_api_domain }}"

  # KYC domain
  NUXT_PUBLIC_KYC_API_BASE_URL_CLIENT: "https://{{ .Values.config.public_api_domain }}"
  NUXT_PUBLIC_KYC_API_BASE_URL_SERVER: "http://{{ .Values.config.internal_api_domain }}"

  NUXT_PUBLIC_TRACKING_API_BASE_URL: "https://{{ .Values.config.public_tracking_domain }}"

  # OTEL configuration
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://k8s-monitoring-alloy.monitoring.svc.cluster.local:4317"
  OTEL_BSP_SCHEDULE_DELAY: "2000"
  OTEL_BSP_MAX_EXPORT_BATCH_SIZE: "1024"
  OTEL_BSP_MAX_QUEUE_SIZE: "4096"
  OTEL_BSP_EXPORT_TIMEOUT: "15000"
  OTEL_BSP_MAX_CONCURRENT_EXPORTS: "2"
