apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app: "{{ .Release.Name }}"
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}"
    spec:
      priorityClassName: "{{ .Release.Name }}-high-priority"
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - api
                topologyKey: kubernetes.io/hostname
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - "{{ .Release.Name }}"
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: "{{ .Release.Name }}"
          image: "050295693931.dkr.ecr.eu-west-1.amazonaws.com/frontend:{{ .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: "1"
              memory: "256Mi"
          envFrom:
            - configMapRef:
                name: "{{ .Release.Name }}"
