apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app: "{{ .Release.Name }}"
spec:
  revisionHistoryLimit: 3
  replicas: 3
  selector:
    matchLabels:
      app: "{{ .Release.Name }}"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}"
    spec:
      # Improved pod spreading
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: "{{ .Release.Name }}"
      # Keep anti-affinity as backup
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - "{{ .Release.Name }}"
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: "{{ .Release.Name }}"
          image: "891377191070.dkr.ecr.sa-east-1.amazonaws.com/girobet-frontend:{{ .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: "{{ .Release.Name }}"
