apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: "{{ .Release.Name }}"
spec:
  virtualhost:
    fqdn: "{{ .Values.config.public_domain }}"
    tls:
      secretName: "{{ .Release.Name }}-certificate"
  routes:
    - timeoutPolicy:
        response: 30s
      services:
        - name: "{{ .Release.Name }}"
          port: 80
