apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: "{{ .Release.Name }}-girobet"
spec:
  virtualhost:
    fqdn: staging.girobet.vip
    tls:
      secretName: "{{ .Release.Name }}-girobet-certificate"
  routes:
    - timeoutPolicy:
        response: 30s
      services:
        - name: "{{ .Release.Name }}"
          port: 80
