apiVersion: v2
name: frontend
description: A Helm chart for deploying the casino frontend application on Kubernetes
type: application
version: 1.0.0
appVersion: "latest"
keywords:
  - frontend
  - nuxt
  - gambling