name: Release

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::891377191070:role/github-actions-role
          role-session-name: github-actions
          aws-region: sa-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: 891377191070
          mask-password: "true"

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          NUXT_PUBLIC_RELEASE: ${{ github.sha }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          build-args: |
            VERSION=${{ github.sha }}
          tags: |
            891377191070.dkr.ecr.sa-east-1.amazonaws.com/girobet-frontend
            891377191070.dkr.ecr.sa-east-1.amazonaws.com/girobet-frontend:${{ github.sha }}

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@master
        with:
          format: 'YYYYMMDDHHmmss'

      - name: Helm Package
        run: helm package helm --app-version ${{ github.sha }} --version 1.0.0-${{ steps.time.outputs.time }}

      - name: Helm Push
        run: helm push girobet-frontend-*.tgz oci://891377191070.dkr.ecr.sa-east-1.amazonaws.com/

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Setup ArgoCD CLI
        uses: imajeetyadav/argocd-cli@v1

      - run: |
          argocd app sync girobet-frontend
        env:
          ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
          ARGOCD_SERVER: argocd.taild2b874.ts.net