name: Staging Release

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::050295693931:role/github-actions-role
          role-session-name: github-actions
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: "050295693931"
          mask-password: "true"

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          NUXT_PUBLIC_RELEASE: ${{ github.sha }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          build-args: |
            VERSION=${{ github.sha }}
          tags: |
            050295693931.dkr.ecr.eu-west-1.amazonaws.com/frontend/staging
            050295693931.dkr.ecr.eu-west-1.amazonaws.com/frontend/staging:${{ github.sha }}

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@master
        with:
          format: "YYYYMMDDHHmmss"

      - name: Helm Package
        run: helm package helm --app-version ${{ github.sha }} --version 1.0.0-${{ steps.time.outputs.time }}

      - name: Helm Push
        run: helm push frontend-*.tgz oci://050295693931.dkr.ecr.eu-west-1.amazonaws.com/frontend/staging